export const coinSpotCsv = [
  { key: 'Transaction Date' },
  { key: 'Type' },
  { key: 'Market' },
  { key: 'Amount' },
  { key: 'Rate inc. fee' },
  { key: 'Rate ex. fee' },
  { key: 'Fee' },
  { key: 'Fee AUD (inc GST)' },
  { key: 'GST AUD' },
  { key: 'Total AUD' },
  { key: 'Total (inc GST)' },
];

export const swyftxCsv = [
  { key: 'Date' },
  { key: 'Time' },
  { key: 'Event' },
  { key: 'Asset' },
  { key: 'Amount' },
  { key: 'Currency' },
  { key: 'Value' },
  { key: 'Rate' },
  { key: 'AUD Value Fee' },
  { key: 'AUD Value' },
  { key: 'Fee Amount' },
  { key: 'Fee Asset' },
  { key: 'GST' },
  { key: 'ExGST' },
  { key: 'Deposited To' },
  { key: 'Withdrawn To' },
  { key: 'Withdrawal Fee' },
  { key: 'Reference' },
  { key: 'Transaction ID' },
  { key: 'UUID' },
];
