export const assets = {
  '1': { code: 'AUD', name: 'Australian Dollars' },
  '2': { code: 'USDT', name: 'USD Tether' },
  '3': { code: 'BTC', name: 'Bitcoin' },
  '4': { code: 'TRX', name: 'TRON' },
  '5': { code: 'ETH', name: 'Ethereum' },
  '6': { code: 'XRP', name: 'XRP' },
  '7': { code: 'BCH', name: 'Bitcoin Cash' },
  '8': { code: 'EOS', name: 'EOS' },
  '9': { code: 'XVG', name: 'Verge' },
  '10': { code: 'NEO', name: 'NEO' },
  '11': { code: 'LTC', name: 'Litecoin' },
  '12': { code: 'ADA', name: 'Cardano' },
  '13': { code: 'BNB', name: 'Binance Coin' },
  '14': { code: 'IOTA', name: 'IOTA' },
  '15': { code: 'QTUM', name: 'Qtum' },
  '16': { code: 'ETC', name: 'Ethereum Classic' },
  '17': { code: 'WTC', name: 'Waltonchain' },
  '18': { code: 'ZRX', name: '0x' },
  '19': { code: 'SUB', name: 'Substratum' },
  '20': { code: 'OMG', name: 'OMG Network' },
  '21': { code: 'XMR', name: 'Monero' },
  '22': { code: 'ZEC', name: 'Zcash' },
  '23': { code: 'BAT', name: 'Basic Attention Token' },
  '24': { code: 'LSK', name: 'Lisk' },
  '25': { code: 'SALT', name: 'SALT' },
  '26': { code: 'FUN', name: 'FunFair' },
  '27': { code: 'MCO', name: 'Monaco' },
  '28': { code: 'POWR', name: 'Power Ledger' },
  '29': { code: 'VGX', name: 'Voyager' },
  '30': { code: 'WAVES', name: 'Waves' },
  '31': { code: 'ADX', name: 'AdEx' },
  '32': { code: 'KMD', name: 'Komodo' },
  '33': { code: 'GBP', name: 'Great British Pound' },
  '34': { code: 'JPY', name: 'Japanese Yen' },
  '35': { code: 'EUR', name: 'Euro' },
  '36': { code: 'USD', name: 'US Dollars' },
  '37': { code: 'BTT', name: 'BitTorrent' },
  '38': { code: 'DASH', name: 'Dash' },
  '39': { code: 'DENT', name: 'Dent' },
  '40': { code: 'HOT', name: 'Holo' },
  '41': { code: 'LINK', name: 'Chainlink' },
  '42': { code: 'MTL', name: 'Metal' },
  '43': { code: 'NANO', name: 'Nano' },
  '44': { code: 'NPXS', name: 'Pundi X' },
  '45': { code: 'XLM', name: 'Stellar Lumens' },
  '46': { code: 'ZIL', name: 'Zilliqa' },
  '47': { code: 'SYS', name: 'Syscoin' },
  '48': { code: 'PPT', name: 'Populous' },
  '49': { code: 'VET', name: 'VeChain' },
  '50': { code: 'ONT', name: 'Ontology' },
  '51': { code: 'XEM', name: 'NEM' },
  '52': { code: 'BTG', name: 'Bitcoin Gold' },
  '53': { code: 'USDC', name: 'USD Coin' },
  '54': { code: 'DCR', name: 'Decred' },
  '55': { code: 'TUSD', name: 'TrueUSD' },
  '56': { code: 'REP', name: 'Augur' },
  '57': { code: 'BCD', name: 'Bitcoin Diamond' },
  '58': { code: 'RVN', name: 'Ravencoin' },
  '59': { code: 'BTS', name: 'BitShares' },
  '60': { code: 'ICX', name: 'ICON' },
  '61': { code: 'PAX', name: 'Paxos Standard Token' },
  '62': { code: 'AE', name: 'Aeternity' },
  '63': { code: 'SC', name: 'Siacoin' },
  '64': { code: 'ATOM', name: 'Cosmos' },
  '65': { code: 'STEEM', name: 'Steem' },
  '66': { code: 'ENJ', name: 'Enjin Coin' },
  '67': { code: 'THETA', name: 'THETA' },
  '68': { code: 'STRAT', name: 'Stratis' },
  '69': { code: 'SNT', name: 'Status' },
  '70': { code: 'GNT', name: 'Golem' },
  '71': { code: 'ELF', name: 'aelf' },
  '72': { code: 'ARDR', name: 'Ardor' },
  '73': { code: 'DOGE', name: 'Dogecoin' },
  '74': { code: 'NXS', name: 'Nexus' },
  '75': { code: 'IOST', name: 'IOST' },
  '76': { code: 'ZEN', name: 'Horizen' },
  '77': { code: 'MANA', name: 'Decentraland' },
  '79': { code: 'XTZ', name: 'Tezos' },
  '80': { code: 'RLC', name: 'iExec RLC' },
  '81': { code: 'HBAR', name: 'Hedera Hashgraph' },
  '82': { code: 'GAS', name: 'Gas' },
  '83': { code: 'ONG', name: 'Ontology Gas' },
  '84': { code: 'STX', name: 'Stacks' },
  '85': { code: 'LEND', name: 'Aave' },
  '86': { code: 'ALGO', name: 'Algorand' },
  '87': { code: 'ENG', name: 'Enigma' },
  '88': { code: 'AGI', name: 'SingularityNET' },
  '89': { code: 'KNC', name: 'Kyber Network' },
  '90': { code: 'TNT', name: 'Tierion' },
  '91': { code: 'AION', name: 'Aion' },
  '92': { code: 'REN', name: 'Ren' },
  '93': { code: 'WRX', name: 'WazirX' },
  '94': { code: 'HC', name: 'HyperCash' },
  '95': { code: 'BUSD', name: 'Binance USD' },
  '96': { code: 'XZC', name: 'ZCoin' },
  '97': { code: 'FTT', name: 'FTX Token' },
  '98': { code: 'LRC', name: 'Loopring' },
  '99': { code: 'CHZ', name: 'Chiliz' },
  '100': { code: 'WIN', name: 'WINk' },
  '101': { code: 'BRD', name: 'Bread' },
  '102': { code: 'FET', name: 'Fetch.ai' },
  '103': { code: 'LTO', name: 'LTO Network' },
  '104': { code: 'WABI', name: 'Tael' },
  '105': { code: 'NKN', name: 'NKN' },
  '106': { code: 'PERL', name: 'Perlin' },
  '107': { code: 'RCN', name: 'Ripio Credit Network' },
  '108': { code: 'DATA', name: 'Streamr DATAcoin' },
  '109': { code: 'KAVA', name: 'Kava' },
  '110': { code: 'GRS', name: 'Groestlcoin' },
  '111': { code: 'OGN', name: 'Origin Protocol' },
  '112': { code: 'COTI', name: 'COTI' },
  '113': { code: 'ARK', name: 'Ark' },
  '115': { code: 'SNX', name: 'Synthetix Network Token' },
  '116': { code: 'ERD', name: 'Elrond' },
  '117': { code: 'COMP', name: 'Compound' },
  '118': { code: 'BAND', name: 'BAND' },
  '119': { code: 'DGB', name: 'DigiByte' },
  '120': { code: 'BNT', name: 'Bancor' },
  '121': { code: 'DOT', name: 'Polkadot' },
  '122': { code: 'FTM', name: 'Fantom' },
  '123': { code: 'IOTX', name: 'IoTeX' },
  '124': { code: 'MATIC', name: 'Polygon' },
  '125': { code: 'MFT', name: 'Mainframe' },
  '126': { code: 'NULS', name: 'Nuls' },
  '127': { code: 'OCEAN', name: 'Ocean Protocol' },
  '128': { code: 'ONE', name: 'Harmony' },
  '129': { code: 'REQ', name: 'Request Network' },
  '130': { code: 'SOL', name: 'Solana' },
  '131': { code: 'SRM', name: 'Serum' },
  '132': { code: 'SXP', name: 'Swipe' },
  '133': { code: 'TFUEL', name: 'Theta Fuel' },
  '134': { code: 'EGLD', name: 'Elrond eGold' },
  '135': { code: 'KSM', name: 'Kusama' },
  '136': { code: 'YFI', name: 'yearn.finance' },
  '137': { code: 'TRB', name: 'Tellor' },
  '138': { code: 'MKR', name: 'Maker' },
  '139': { code: 'RSR', name: 'Reserve Rights' },
  '140': { code: 'PAXG', name: 'PAX Gold' },
  '141': { code: 'UNI', name: 'Uniswap' },
  '142': { code: 'UMA', name: 'UMA' },
  '143': { code: 'YFII', name: 'DFI.Money' },
  '144': { code: 'HIVE', name: 'Hive' },
  '145': { code: 'STORJ', name: 'Storj' },
  '146': { code: 'JST', name: 'JUST' },
  '147': { code: 'IRIS', name: 'IRISnet' },
  '148': { code: 'DIA', name: 'DIA' },
  '149': { code: 'TOMO', name: 'TomoChain' },
  '150': { code: 'WAN', name: 'Wanchain' },
  '151': { code: 'BZRX', name: 'bZx Protocol' },
  '152': { code: 'ANKR', name: 'Ankr' },
  '153': { code: 'BLZ', name: 'Bluzelle' },
  '154': { code: 'NMR', name: 'Numeraire' },
  '155': { code: 'SAND', name: 'The Sandbox' },
  '156': { code: 'ARPA', name: 'ARPA Chain' },
  '157': { code: 'CELR', name: 'Celer Network' },
  '158': { code: 'VTHO', name: 'VeThor Token' },
  '159': { code: 'LOOM', name: 'Loom Network' },
  '160': { code: 'CVC', name: 'Civic' },
  '161': { code: 'AST', name: 'AirSwap' },
  '162': { code: 'CHR', name: 'Chromia' },
  '163': { code: 'NAS', name: 'Nebulas' },
  '164': { code: 'DUSK', name: 'Dusk Network' },
  '165': { code: 'BAL', name: 'Balancer' },
  '166': { code: 'STPT', name: 'Standard Tokenization Protocol' },
  '167': { code: 'PNT', name: 'pNetwork' },
  '168': { code: 'COCOSOLD', name: 'Cocos-BCX Old' },
  '169': { code: 'FIO', name: 'FIO Protocol' },
  '170': { code: 'KEY', name: 'Selfkey' },
  '171': { code: 'DREPOLD', name: 'DREP Old' },
  '172': { code: 'CTSI', name: 'Cartesi' },
  '173': { code: 'VITE', name: 'VITE' },
  '174': { code: 'NAV', name: 'NAV Coin' },
  '175': { code: 'NEBL', name: 'Neblio' },
  '176': { code: 'ANT', name: 'Aragon' },
  '177': { code: 'MDT', name: 'Measurable Data Token' },
  '178': { code: 'TCT', name: 'TokenClub Token' },
  '179': { code: 'TROY', name: 'Troy' },
  '180': { code: 'MBL', name: 'MovieBloc' },
  '181': { code: 'OXT', name: 'Orchid' },
  '182': { code: 'AVAX', name: 'Avalanche' },
  '183': { code: 'SUNOLD', name: 'SUN Old' },
  '184': { code: 'SUSHI', name: 'Sushi' },
  '185': { code: 'LUNA', name: 'Terra' },
  '186': { code: 'WNXM', name: 'Wrapped NXM' },
  '187': { code: 'RUNE', name: 'THORChain' },
  '188': { code: 'CRV', name: 'Curve' },
  '189': { code: 'HNT', name: 'Helium' },
  '190': { code: 'NZD', name: 'New Zealand Dollars' },
  '191': { code: 'SCRT', name: 'Secret' },
  '192': { code: 'ORN', name: 'Orion Protocol' },
  '193': { code: 'UTK', name: 'Utrust' },
  '194': { code: 'XVS', name: 'Venus' },
  '195': { code: 'AAVE', name: 'Aave' },
  '196': { code: 'FIL', name: 'Filecoin' },
  '197': { code: 'INJ', name: 'Injective Protocol' },
  '198': { code: 'FLM', name: 'Flamingo' },
  '199': { code: 'WING', name: 'Wing Token' },
  '200': { code: 'ALPHA', name: 'Alpha Finance Lab' },
  '201': { code: 'BEL', name: 'Bella Protocol' },
  '202': { code: 'POLY', name: 'Polymath' },
  '203': { code: 'VIDT', name: 'VIDT Datalink' },
  '204': { code: 'BOT', name: 'Bounce Token' },
  '205': { code: 'NEAR', name: 'NEAR Protocol' },
  '206': { code: 'DNT', name: 'district0x' },
  '207': { code: 'AKRO', name: 'Akropolis' },
  '208': { code: 'STRAX', name: 'STRAX Token' },
  '209': { code: 'GLM', name: 'Golem' },
  '210': { code: 'GRT', name: 'The Graph' },
  '211': { code: 'AUDIO', name: 'Audius' },
  '212': { code: 'GVT', name: 'Genesis Vision' },
  '213': { code: 'QSP', name: 'Quantstamp' },
  '214': { code: 'CND', name: 'Cindicator' },
  '215': { code: 'VIBE', name: 'VIBE' },
  '216': { code: 'WPR', name: 'WePower' },
  '217': { code: 'QLC', name: 'QLC Chain' },
  '218': { code: 'MITH', name: 'Mithril' },
  '219': { code: 'COS', name: 'Contentos' },
  '220': { code: 'STMX', name: 'StormX' },
  '221': { code: 'AVA', name: 'Travala.com' },
  '222': { code: 'WBTC', name: 'Wrapped Bitcoin' },
  '223': { code: 'MDA', name: 'Moeda Loyalty Points' },
  '224': { code: 'AERGO', name: 'Aergo' },
  '225': { code: 'HARD', name: 'HARD Protocol' },
  '226': { code: 'FOR', name: 'ForTube' },
  '227': { code: 'SKL', name: 'SKALE Network' },
  '228': { code: 'DLT', name: 'Agrello' },
  '229': { code: 'OST', name: 'OST' },
  '230': { code: 'PSG', name: 'Paris Saint-Germain Fan Token' },
  '231': { code: 'JUV', name: 'Juventus Fan Token' },
  '232': { code: 'MTH', name: 'Monetha' },
  '233': { code: 'OAX', name: 'openANX' },
  '234': { code: 'EVX', name: 'Everex' },
  '235': { code: 'VIB', name: 'Viberate' },
  '236': { code: 'RDN', name: 'Raiden Network Token' },
  '237': { code: 'BCPT', name: 'BlockMason Credit Protocol' },
  '238': { code: 'CDT', name: 'Blox' },
  '239': { code: 'AMB', name: 'Ambrosus' },
  '240': { code: 'CMT', name: 'CyberMiles' },
  '241': { code: 'GO', name: 'GoChain' },
  '242': { code: 'CTXC', name: 'Cortex' },
  '243': { code: 'POA', name: 'POA Network' },
  '244': { code: 'ROSE', name: 'Oasis Network' },
  '245': { code: 'VIA', name: 'Viacoin' },
  '246': { code: 'SKY', name: 'Skycoin' },
  '247': { code: 'QKC', name: 'QuarkChain' },
  '248': { code: 'CTK', name: 'CertiK' },
  '249': { code: 'YOYO', name: 'YOYOW' },
  '250': { code: '1INCH', name: '1inch' },
  '251': { code: 'CELO', name: 'Celo' },
  '252': { code: 'COCOS', name: 'Cocos-BCX' },
  '253': { code: 'FIRO', name: 'Firo' },
  '254': { code: 'TWT', name: 'Trust Wallet Token' },
  '255': { code: 'TRU', name: 'TrueFi' },
  '256': { code: 'REEF', name: 'Reef Finance' },
  '257': { code: 'AXS', name: 'Axie Infinity' },
  '258': { code: 'BTCSTOLD', name: 'Bitcoin Standard Hashrate Token OLD' },
  '259': { code: 'SNMOLD', name: 'SONM Old' },
  '260': { code: 'APPC', name: 'AppCoins' },
  '261': { code: 'IDEX', name: 'IDEX' },
  '262': { code: 'UNFI', name: 'Unifi Protocol DAO' },
  '263': { code: 'DODO', name: 'DODO' },
  '264': { code: 'CAKE', name: 'PancakeSwap' },
  '265': { code: 'RIF', name: 'RSK Infrastructure Framework' },
  '266': { code: 'NBS', name: 'New BitShares' },
  '268': { code: 'FRONT', name: 'Frontier' },
  '269': { code: 'ACM', name: 'AC Milan Fan Token' },
  '270': { code: 'GXS', name: 'GXChain' },
  '271': { code: 'AUCTION', name: 'Auction' },
  '272': { code: 'BADGER', name: 'Badger DAO' },
  '273': { code: 'OM', name: 'MANTRA DAO' },
  '274': { code: 'LINA', name: 'Linear' },
  '275': { code: 'BTCST', name: 'Bitcoin Standard Hashrate Token' },
  '276': { code: 'DEGO', name: 'Dego Finance' },
  '277': { code: 'RAMP', name: 'RAMP' },
  '278': { code: 'PERP', name: 'Perpetual Protocol' },
  '279': { code: 'LIT', name: 'Litentry' },
  '280': { code: 'TVK', name: 'Terra Virtua' },
  '281': { code: 'FIS', name: 'Stafi' },
  '282': { code: 'PHA', name: 'Phala.Network' },
  '283': { code: 'ALICE', name: 'My Neighbor Alice' },
  '284': { code: 'DREP', name: 'DREP' },
  '285': { code: 'PUNDIX', name: 'Pundi X' },
  '286': { code: 'EPS', name: 'Ellipsis' },
  '287': { code: 'SUPER', name: 'SuperFarm' },
  '288': { code: 'AUTO', name: 'Auto' },
  '289': { code: 'ASR', name: 'AS Roma Fan Token' },
  '290': { code: 'GTO', name: 'Gifto' },
  '291': { code: 'CFX', name: 'Conflux Network' },
  '292': { code: 'SNM', name: 'SONM' },
  '293': { code: 'SHIB', name: 'SHIBA INU' },
  '294': { code: 'AGIX', name: 'SingularityNET Token' },
  '295': { code: 'SUN', name: 'SUN' },
  '296': { code: 'TORN', name: 'Tornado Cash' },
  '297': { code: 'GTC', name: 'Gitcoin' },
  '298': { code: 'MDX', name: 'Mdex' },
  '299': { code: 'MASK', name: 'Mask Network' },
  '300': { code: 'BAR', name: 'FC Barcelona Fan Token BAR' },
  '301': { code: 'MIR', name: 'Mirror Protocol' },
  '302': { code: 'TLM', name: 'Alien Worlds' },
  '303': { code: 'KEEP', name: 'Keep Network' },
  '304': { code: 'ERN', name: 'Ethernity Chain' },
  '305': { code: 'LPT', name: 'Livepeer' },
  '306': { code: 'QUICK', name: 'QuickSwap' },
  '307': { code: 'NU', name: 'NuCypher' },
  '308': { code: 'POLS', name: 'Polkastarter' },
  '309': { code: 'FORTH', name: 'Ampleforth Governance Token' },
  '310': { code: 'ICP', name: 'Internet Computer' },
  '311': { code: 'XYM', name: 'Symbol' },
  '312': { code: 'QNT', name: 'Quant' },
  '313': { code: 'FLOW', name: 'Flow' },
  '315': { code: 'CKB', name: 'CKB' },
  '319': { code: 'USDP', name: 'Pax Dollar' },
  '320': { code: 'AR', name: 'Arweave' },
  '321': { code: 'SSV', name: 'SSV Token' },
  '322': { code: 'ILV', name: 'Illuvium' },
  '323': { code: 'RAY', name: 'Raydium' },
  '324': { code: 'DYDX', name: 'dYdX' },
  '325': { code: 'CLV', name: 'Clover Finance' },
  '326': { code: 'TRIBE', name: 'Tribe' },
  '327': { code: 'FARM', name: 'Harvest Finance' },
  '328': { code: 'BOND', name: 'BarnBridge' },
  '329': { code: 'BURGER', name: 'Burger Swap' },
  '330': { code: 'DEXE', name: 'DeXe' },
  '331': { code: 'MBOX', name: 'MOBOX' },
  '332': { code: 'SFP', name: 'SafePal' },
  '333': { code: 'SLP', name: 'Smooth Love Potion' },
  '334': { code: 'C98', name: 'Coin98' },
  '335': { code: 'YGG', name: 'Yield Guild Games' },
  '336': { code: 'MLN', name: 'Enzyme' },
  '338': { code: 'GALA', name: 'Gala' },
  '339': { code: 'GNO', name: 'Gnosis' },
  '340': { code: 'BAKE', name: 'BakeryToken' },
  '341': { code: 'AGLD', name: 'Adventure Gold' },
  '342': { code: 'TKO', name: 'Tokocrypto' },
  '343': { code: 'ALPACA', name: 'Alpaca Finance' },
  '344': { code: 'MINA', name: 'Mina' },
  '345': { code: 'MOVR', name: 'Moonriver' },
  '346': { code: 'GHST', name: 'Aavegotchi' },
  '347': { code: 'AMP', name: 'AMP' },
  '348': { code: 'OG', name: 'OG Fan Token' },
  '349': { code: 'PLA', name: 'PlayDapp' },
  '350': { code: 'PROM', name: 'Prometeus' },
  '351': { code: 'RAD', name: 'Radicle' },
  '352': { code: 'RARE', name: 'SuperRare' },
  '353': { code: 'PYR', name: 'Vulcan Forged PYR' },
  '354': { code: 'ATM', name: 'Atlético de Madrid Fan Token' },
  '355': { code: 'QI', name: 'BENQI' },
  '356': { code: 'FIDA', name: 'Bonfida' },
  '357': { code: 'ENS', name: 'Ethereum Name Service' },
  '358': { code: 'FXS', name: 'Frax Share' },
  '359': { code: 'JASMY', name: 'JasmyCoin' },
  '360': { code: 'LAZIO', name: 'Lazio Fan Token' },
  '361': { code: 'CITY', name: 'Manchester City Fan Token' },
  '362': { code: 'OOKI', name: 'OokiDAO' },
  '363': { code: 'SGB', name: 'Songbird' },
  '364': { code: 'BTTC', name: 'BitTorrent' },
  '365': { code: 'XNO', name: 'Nano token' },
};
