import loginBGPng from "../../design-images/login-bg.png";
import loginBigLogo from "../../design-images/login-ctv-big-icon.svg";

const styles = (theme) => ({
  "@global": {
    "*::-webkit-scrollbar": {
      width: "6px",
    },
    "*::-webkit-scrollbar-track": {
      "-webkit-box-shadow": "inset 0 0 6px rgba(0,0,0,0.00)",
      borderRadius: "8px",
      backgroundColor: "#ECEFF4",
    },
    "*::-webkit-scrollbar-thumb": {
      backgroundColor: "#134675", //'rgba(0,0,0,.1)',
      outline: "1px solid #D7E0E7",
      borderRadius: "8px",
    },
  },
  main: {
    background: "#0074cb",
  },
  signInText: {
    // fontSize: "0.95vw !important",
    margin: "3px auto !important",
    fontFamily: "Roboto",
    fontWeight: "500 !important",
    lineHeight: "15px !important",
  },
  signInTextOnReferrals: {
    // fontSize: "0.95vw !important",
    margin: "3px auto !important",
    marginTop: "10px !important",
    fontFamily: "Roboto",
    fontWeight: "500 !important",
    lineHeight: "15px !important",
  },
  grid: {
    width: "28%",
    // marginTop: "120px",
    margin: "auto",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: "90%",
  },
  Box: {
    width: "85%",
    height: "100%",
    margin: "auto",
    textAlign: "center",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    alignItems: "center",
  },
  textfields: {
    color: "white",
    width: "100%",
    marginBottom: "2% !important",
  },
  signInPage: {
    // background: "#0074cb",
    backgroundImage: `url("${loginBGPng}")`,
    backgroundColor: "#0074CB",
    backgroundSize: "cover",
    backgroundRepeat: "no-repeat",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    height: "100vh",
    position: "relative",
  },
  ctvBigLogo: {
    backgroundImage: `url("${loginBigLogo}")`,
    backgroundPosition: "left bottom",
    backgroundRepeat: "no-repeat",
    backgroundSize: "contain",
    opacity: "10%",
    height: "90vh",
    width: "37%",
    position: "absolute",
    left: "-190px",
    bottom: "37px",
    [theme.breakpoints.down("sm")]: {
      bottom: "20%",
    },
  },
  paper: {
    width: "80%",
    paddingTop: "10px",
    paddingBottom: "10px",
    borderRadius: "8px !important",
    boxShadow: "rgba(255, 255, 255, 1) 0px 0px 9px 0px !important",
    maxHeight: "98%",
    padding: "5px 10px",
    // height: "60%",
    [theme.breakpoints.down("sm")]: {
      // height: "80%",
    },
  },
  "@media (max-width: 720px)": {
    paper: { height: "95%" },
  },
  signInHeading: {
    fontFamily: "Roboto !important",
    color: "#092c4c",
    fontWeight: "700",
    marginTop: "3%",
    marginBottom: "3%",
  },
  form: {
    // height: "98% !important",
    maxHeight: "100% !important",
    overflowY: "auto",
  },
  signInWithGoogleBtn: {
    fontSize: "18px",
    fontFamily: "Roboto",
    letterSpacing: "0.5px",
    boxSizing: "border-box",
    backgroundColor: "#298bf4",
    padding: "15px",
    borderRadius: "4px",
    width: "100%",
    margin: "5px auto",
    color: "white",
    fontWeight: "600",
    position: "relative",
    "& img": {
      height: "46px",
      position: "absolute",
      top: "2px",
      left: "2px",
    },
    "&:hover": {
      cursor: "pointer",
    },
    marginTop: "6%",
  },
  signInOr: {
    fontFamily: "Roboto",
    marginTop: "2%",
    marginBottom: "2%",
    position: "relative",
    width: "100%",
    "&:before": {
      position: "absolute",
      content: '""',
      background: "#e7eaeb",
      display: "block",
      height: "1px",
      width: "45%",
      top: "11px",
    },
    "&:after": {
      position: "absolute",
      content: '""',
      background: "#e7eaeb",
      display: "block",
      height: "1px",
      width: "45%",
      top: "11px",
      right: "0px",
    },
  },
  eyeIconBox: {
    display: "flex",
    position: "relative",
    width: "100%",
  },
  eyeButton: {
    position: "absolute",
    top: "14px",
    right: "17px",
    cursor: "pointer",
  },
  checkForgotPart: {
    display: "flex !important",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
  },
  rememberMeText: {
    fontWeight: "500 !important",
    fontFamily: "Roboto",
  },
  formControlLabel: {
    marginRight: "0px !important",
    "& path": {
      stroke: "white",
    },
  },
  rememberMeContainer: {
    display: "flex",
    alignItems: "center",
  },
  forgotPassword: {
    fontFamily: "Roboto",
    color: "#005aff",
    fontWeight: "500 !important",
    cursor: "pointer",
  },
  signInButton: {
    fontSize: "18px !important",
    fontFamily: "Roboto !important",
    letterSpacing: "0.5px !important",
    fontWeight: "600 !important",
    textTransform: "unset !important",
    background: "#134675 !important",
    width: "100%",
    padding: "10px !important",
    marginTop: "7px !important",
  },
  notAMember: {
    display: "flex !important",
    justifyContent: "center",
    marginBottom: "3px",
  },
  notAMemberText: { fontWeight: "500 !important", fontFamily: "Roboto" },
  signInAnchor: {
    marginTop: "14px",
    paddingLeft: "5px",
    fontWeight: "500 !important",
    fontFamily: "roboto",
    color: "#005aff",
  },
  copyright: {
    color: "white",
    fontSize: "12px",
  },
  logoBackground: {
    // backgroundImage: `url("${loginBGPng}"),  linear-gradient(to right, rgb(0, 67, 129), rgb(2, 73, 198))`,
    // backgroundImage: `url('../../forms/Signup Logo BG.svg'),  linear-gradient(to right, rgb(1, 77, 50), rgb(2, 99, 98))`,
    // background: "blue",
    // left: "50",
    // top: "50",
    // display: "block",
    position: "absolute",
    backgroundSize: "contain",
    height: "100%",
    width: "100%",
  },
});
export default styles;
