const BLUE_DARK = "#134675";
const BLUE = "#0074CB";
const BLUE_LIGHT = "#E6F4FF";

export const MASTER_PERSONAL_PLAN = [
  {
    id: 1,
    icon: "gold_empty.svg",
    title: "FREE",
    priceValue: "00",
    priceCurrency: "$",
    planFeatures: [
      { text: "Add Clients", value: "Unlimited" },
      { text: "Transaction", value: "Total 10" },
    ],
    description:
      "Lorem Ipsum text for plan features only for or full package dummy text",
    buttonSubmitText: "Active Plan",
    buttonClickUrl: "/home",
    color: "black",
    colorAlt: "white",
    backgroundColorTile: BLUE_LIGHT,
    backgroundColorTileAlt: BLUE,
    buttonSubmitColor: "black",
    buttonSubmitColorAlt: "white",
    buttonSubmitColorBackground: "white",
    buttonSubmitColorBackgroundAlt: BLUE_DARK,
    borderColor: "#C2CFD9",
  },
  {
    id: 2,
    icon: "gold_full.svg",
    title: "PREMIUM",
    priceValue: "150",
    priceCurrency: "$",
    planFeatures: [
      { text: "Add Clients", value: "Unlimited" },
      { text: "Transaction", value: "Total 500" },
      { text: "Reports", value: "Total 100" },
    ],
    description:
      "Lorem Ipsum text for plan features only for or full package dummy text",
    buttonSubmitText: "Buy Now",
    buttonClickUrl: "/home",
    color: "black",
    colorAlt: "white",
    backgroundColorTile: BLUE_LIGHT,
    backgroundColorTileAlt: BLUE,
    buttonSubmitColor: "black",
    buttonSubmitColorAlt: "white",
    buttonSubmitColorBackground: "white",
    buttonSubmitColorBackgroundAlt: BLUE_DARK,
    borderColor: "#C2CFD9",
  },
];

export const MASTER_PROFESSIONAL_PLAN = [
  {
    id: 3,
    icon: "gold_empty.svg",
    title: "FREE",
    priceValue: "00",
    priceCurrency: "$",
    planFeatures: [
      { text: "Add Clients", value: "Unlimited" },
      { text: "Transaction", value: "Total 10" },
    ],
    description:
      "Lorem Ipsum text for plan features only for or full package dummy text",
    buttonSubmitText: "Active Plan",
    buttonClickUrl: "/home",
    color: "black",
    colorAlt: "white",
    backgroundColorTile: BLUE_LIGHT,
    backgroundColorTileAlt: BLUE,
    buttonSubmitColor: "black",
    buttonSubmitColorAlt: "white",
    buttonSubmitColorBackground: "white",
    buttonSubmitColorBackgroundAlt: BLUE_DARK,
    borderColor: "#C2CFD9",
  },
  {
    id: 4,
    icon: "gold_half.svg",
    title: "ADVANCED",
    priceValue: "100",
    priceCurrency: "$",
    planFeatures: [
      { text: "Add Clients", value: "Unlimited" },
      { text: "Transaction", value: "Total 100" },
      { text: "Reports", value: "Total 10" },
    ],
    description:
      "Lorem Ipsum text for plan features only for or full package dummy text",
    buttonSubmitText: "Buy Now",
    buttonClickUrl: "/home",
    color: "black",
    colorAlt: "white",
    backgroundColorTile: BLUE_LIGHT,
    backgroundColorTileAlt: BLUE,
    buttonSubmitColor: "black",
    buttonSubmitColorAlt: "white",
    buttonSubmitColorBackground: "white",
    buttonSubmitColorBackgroundAlt: BLUE_DARK,
    borderColor: "#C2CFD9",
  },
  {
    id: 5,
    icon: "gold_full.svg",
    title: "PREMIUM",
    priceValue: "150",
    priceCurrency: "$",
    planFeatures: [
      { text: "Add Clients", value: "Unlimited" },
      { text: "Transaction", value: "Total 500" },
      { text: "Reports", value: "Total 100" },
    ],
    description:
      "Lorem Ipsum text for plan features only for or full package dummy text",
    buttonSubmitText: "Buy Now",
    buttonClickUrl: "/home",
    color: "black",
    colorAlt: "white",
    backgroundColorTile: BLUE_LIGHT,
    backgroundColorTileAlt: BLUE,
    buttonSubmitColor: "black",
    buttonSubmitColorAlt: "white",
    buttonSubmitColorBackground: "white",
    buttonSubmitColorBackgroundAlt: BLUE_DARK,
    borderColor: "#C2CFD9",
  },
];
